---

- name: Git commit
  block:
    - name: Add changes
      ansible.builtin.command: git add --all .
      args:
        chdir: "{{ git_commit_repo_dir }}"
        warn: no
      changed_when: no
      when: git_commit_add_changes | bool

    - name: Create commit message temporary file
      # To circumvent 255 char commit message limitation
      ansible.builtin.tempfile:
        state: file
        suffix: temp
      changed_when: no  # Temporal files don't alter the state
      register: commit_message_tempfile_result

    - name: Add commit message content to temporary file
      ansible.builtin.copy:
        content: "{{ git_commit_message }}"
        dest: "{{ commit_message_tempfile_result.path }}"
        mode: u=rw,g=r,o=r
      changed_when: no

    - name: Commit to git repository
      ansible.builtin.command: >-
        git {{ git_commit_opts }} commit -F "{{
          commit_message_tempfile_result.path }}"
      args:
        chdir: "{{ git_commit_repo_dir }}"
        warn: no
      register: git_commit_command_result
      failed_when:
        - git_commit_command_result.rc != 0
        - not git_commit_command_result.stdout is search("nothing to commit")
      changed_when: git_commit_command_result.rc == 0
      vars:
        git_commit_username_opt: >-
          {{ (git_commit_username is defined)
             | ternary("-c " + "user.name=" + git_commit_username | default(""),
                       "") }}

        git_commit_email_opt: >-
          {{ (git_commit_email is defined)
             | ternary("-c "
                       + "user.email="
                       + git_commit_email | default(""),
                       "") }}

        git_commit_opts: >-
          {{ git_commit_username_opt }} {{ git_commit_email_opt }}

      environment:
        LANGUAGE: en_US

    - name: Remove commit message temporary file
      ansible.builtin.file:
        path: "{{ commit_message_tempfile_result.path }}"
        state: absent
      when: commit_message_tempfile_result.path is defined
      changed_when: no

    - name: Setup fact indicating commit result
      ansible.builtin.set_fact:
        git_commit_result: "{{ git_commit_command_result }}"

    - name: Push changes
      when: git_commit_result is changed
      block:
        - name: Manage git ssh wrapper
          block:
            - name: Create temporary file for git ssh wrapper
              ansible.builtin.tempfile:
                state: file
              register: git_commit_ssh_wrapper_tmp_result

            - name: Setup git ssh wrapper
              ansible.builtin.template:
                dest: "{{ git_commit_ssh_wraper }}"
                src: ssh_wrapper.sh.j2
                mode: "0750"
          when: git_commit_key_file is defined

        - name: Perform git push
          block:
            - name: Push changes to git repository
              ansible.builtin.command: >-
                git push
                {{ git_commit_push_repo }}
                {{ git_commit_push_branch }}
              args:
                chdir: "{{ git_commit_repo_dir }}"
                warn: no
              when:
                - git_commit_push_repo is defined
                - git_commit_push_repo | length > 0
                - git_commit_push_branch is defined
                - git_commit_push_branch | length > 0

            - name: Push changes to origin/master
              ansible.builtin.command: git --no-pager push origin master
              args:
                chdir: "{{ git_commit_repo_dir }}"
                warn: no
              register: git_commit_push_origin_master_result
              changed_when: >-
                git_commit_push_origin_master_result.stderr
                is search("master -> master")
              when: git_commit_push_origin_master | bool
          environment:
            LANGUAGE: en_US
            GIT_SSH: "{{ git_commit_ssh_wraper }}"

        - name: Remove temporary file for git ssh wrapper
          ansible.builtin.file:
            path: "{{ git_commit_ssh_wraper }}"
            state: absent
          when: git_commit_key_file is defined
  vars:
    git_commit_ssh_wraper: "{{ git_commit_ssh_wrapper_tmp_result.path }}"
  tags:
    - role::git_commit
